In [1]:
import numpy as np
import pandas as pd

In [6]:
c=['Sample code number','Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape','Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Bland Chromatin','Bland Chromatin','Class']
df=pd.read_csv("breast-cancer-wisconsin.data")
df.columns=c
df

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1002945                5                        4   
1               1015425                3                        1   
2               1016277                6                        8   
3               1017023                4                        1   
4               1017122                8                       10   
..                  ...              ...                      ...   
693              776715                3                        1   
694              841769                2                        1   
695              888820                5                       10   
696              897471                4                        8   
697              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           4                  5                            7   
1                           1                  1                            2   
2                           8                  1                            3   
3                           1                  3                            2   
4                          10                  8                            7   
..                        ...                ...                          ...   
693                         1                  1                            3   
694                         1                  1                            2   
695                        10                  3                            7   
696                         6                  4                            3   
697                         8                  5                            4   

    Bare Nuclei  Bland Chromatin  Bland Chromatin  Bland Chromatin  Class  
0            10                3                2                1      2  
1             2                3                1                1      2  
2             4                3                7                1      2  
3             1                3                1                1      2  
4            10                9                7                1      4  
..          ...              ...              ...              ...    ...  
693           2                1                1                1      2  
694           1                1                1                1      2  
695           3                8               10                2      4  
696           4               10                6                1      4  
697           5               10                4                1      4  

[698 rows x 11 columns]

In [7]:
df.drop('Sample code number',axis=1,inplace=True)

In [8]:
z=df.values
print(z)
for i in z:
  print(i)

[[5 4 4 ... 2 1 2]
 [3 1 1 ... 1 1 2]
 [6 8 8 ... 7 1 2]
 ...
 [5 10 10 ... 10 2 4]
 [4 8 6 ... 6 1 4]
 [4 8 8 ... 4 1 4]]
[5 4 4 5 7 '10' 3 2 1 2]
[3 1 1 1 2 '2' 3 1 1 2]
[6 8 8 1 3 '4' 3 7 1 2]
[4 1 1 3 2 '1' 3 1 1 2]
[8 10 10 8 7 '10' 9 7 1 4]
[1 1 1 1 2 '10' 3 1 1 2]
[2 1 2 1 2 '1' 3 1 1 2]
[2 1 1 1 2 '1' 1 1 5 2]
[4 2 1 1 2 '1' 2 1 1 2]
[1 1 1 1 1 '1' 3 1 1 2]
[2 1 1 1 2 '1' 2 1 1 2]
[5 3 3 3 2 '3' 4 4 1 4]
[1 1 1 1 2 '3' 3 1 1 2]
[8 7 5 10 7 '9' 5 5 4 4]
[7 4 6 4 6 '1' 4 3 1 4]
[4 1 1 1 2 '1' 2 1 1 2]
[4 1 1 1 2 '1' 3 1 1 2]
[10 7 7 6 4 '10' 4 1 2 4]
[6 1 1 1 2 '1' 3 1 1 2]
[7 3 2 10 5 '10' 5 4 4 4]
[10 5 5 3 6 '7' 7 10 1 4]
[3 1 1 1 2 '1' 2 1 1 2]
[8 4 5 1 2 '?' 7 3 1 4]
[1 1 1 1 2 '1' 3 1 1 2]
[5 2 3 4 2 '7' 3 6 1 4]
[3 2 1 1 1 '1' 2 1 1 2]
[5 1 1 1 2 '1' 2 1 1 2]
[2 1 1 1 2 '1' 2 1 1 2]
[1 1 3 1 2 '1' 1 1 1 2]
[3 1 1 1 1 '1' 2 1 1 2]
[2 1 1 1 2 '1' 3 1 1 2]
[10 7 7 3 8 '5' 7 4 3 4]
[2 1 1 2 2 '1' 3 1 1 2]
[3 1 2 1 2 '1' 2 1 1 2]
[2 1 1 1 2 '1' 2 1 1 2]
[10 10 10 8 6 '1' 8 9 1 

In [9]:
df.drop(df[df['Bare Nuclei'] == '?'].index, inplace=True)
df['Bare Nuclei'] = df['Bare Nuclei'].astype(int)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 682 entries, 0 to 697
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Clump Thickness              682 non-null    int64
 1   Uniformity of Cell Size      682 non-null    int64
 2   Uniformity of Cell Shape     682 non-null    int64
 3   Marginal Adhesion            682 non-null    int64
 4   Single Epithelial Cell Size  682 non-null    int64
 5   Bare Nuclei                  682 non-null    int32
 6   Bland Chromatin              682 non-null    int64
 7   Bland Chromatin              682 non-null    int64
 8   Bland Chromatin              682 non-null    int64
 9   Class                        682 non-null    int64
dtypes: int32(1), int64(9)
memory usage: 55.9 KB


In [11]:
x=df.drop('Class',axis=1).values
y=df['Class'].values

In [12]:
x

array([[ 5,  4,  4, ...,  3,  2,  1],
       [ 3,  1,  1, ...,  3,  1,  1],
       [ 6,  8,  8, ...,  3,  7,  1],
       ...,
       [ 5, 10, 10, ...,  8, 10,  2],
       [ 4,  8,  6, ..., 10,  6,  1],
       [ 4,  8,  8, ..., 10,  4,  1]], dtype=int64)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:

def svm(l,epochs,X,Y):
    w=np.zeros(len(x[0]))
    b=0
    for i,k in enumerate(X):
        if Y[i]*(w@X[i]-b)>=1:
          w=w-2*l*w
        else:
          w=w-y[i]@x[i]

In [17]:
svm(0.1,1,x,y)

# t=x[0]
# w=np.zeros(len(x[0]))
# print(w@t)

# print(w@x[0])
# for i in x:
#   print(i)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)