In [20]:
import numpy as np

In [21]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[0]])


input_nodes=2
hidden_nodes=2
output_nodes=1

w1=np.random.uniform(low=-1,high=1,size=(input_nodes,hidden_nodes))
w2=np.random.uniform(low=-1,high=1,size=(hidden_nodes,output_nodes))

b1=np.random.uniform(low=-1,high=1,size=(1,hidden_nodes))
b2=np.random.uniform(low=-1,high=1,size=(1,output_nodes))

print(w1)
print(w2)
print(b1)
print(b2)


[[ 0.01360746 -0.53415597]
 [ 0.53512071 -0.32880334]]
[[ 0.01522486]
 [-0.0910962 ]]
[[0.52587016 0.21187999]]
[[-0.49352437]]


In [22]:
mae=0
index=0      # for output (y) 
l=0.1
el=np.array([])

i=np.array([1,1,1])
# same as [[1,1,1]]
w=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
print(i.shape)
print(w.shape)
print(i@w)


(3,)
(3, 4)
[15 18 21 24]


In [23]:
i=[1,1,1]
w=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
np.dot(i,w)


array([15, 18, 21, 24])

In [24]:
inputs=np.array([1,2,3,2.5])
print(inputs.shape)
w=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
np.dot(w,inputs)

(4,)


array([24., 58., 92.])

#### suppose if there are 4 inputs and 3 hidden neuron which means 4x3 matrix will be weight matrix
#### In a weight matrix W of dimensions m x n, each column represents the weights of one neuron in the next layer.

In [25]:
# i=np.array([[1,1,1,1]])
# print(i.shape)
# w=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
# np.dot(i,w)
import numpy as np

In [26]:
def act(x):
    return 1/(1+np.exp(-x))
def bound(x):
    return np.clip(x,-1,1)

In [27]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[0]])


input_nodes=2
hidden_nodes=2
output_nodes=1

w1=np.random.uniform(low=-1,high=1,size=(input_nodes,hidden_nodes))
w2=np.random.uniform(low=-1,high=1,size=(hidden_nodes,output_nodes))

b1=np.random.uniform(low=-1,high=1,size=(1,hidden_nodes))
b2=np.random.uniform(low=-1,high=1,size=(1,output_nodes))

print(w1)
print(w2)
print(b1)
print(b2)


[[-0.38328979  0.92211194]
 [ 0.69269428  0.79720527]]
[[-0.58273326]
 [ 0.01451159]]
[[ 0.88449055 -0.40286921]]
[[0.8439646]]


In [28]:
me=0
mae=0
index=0      # for output (y) 
l=0.1
el=np.array([])

# for i in range(1000):
#     me=0
#     mae=0
x=np.array([[0,1]])
for i in x:   
        print(i)
        print(i.shape)
        hidden_output=act(i@w1+b1)  # 1x2
        final_output=act(hidden_output@w2+b2) #1x1

        #w2= 2x1
        final_error=final_output*(1-final_output)*(y[index]-final_output) #1x1  
        hidden_error=hidden_output*(1-hidden_output)*(final_error@w2.T) #should be 1x2 #print((w2@final_error).T) also works

        me+=final_error
        
        #w1 2x2
        #i 1x2
        w2=bound(w2+(l*(hidden_output.T@final_error)))

        # i 1x2 h 1x2  i.T 2x1,h 1x2 = 2x2 (w1)
        
        print(hidden_error.T@i.reshape(1,2))
        print(i.reshape(1,2).T@hidden_error)

#         w1=bound(w1+(l*(i.reshape(1,2).T@hidden_error)))

        b2=bound(b2+(l*final_error))  #?
        b1=bound(b1+(l*hidden_error))

        index=(index+1)%4
        
#     me=me/4
#     el=np.append(el,me)
# print(el)
    
    

[0 1]
(2,)
[[ 0.          0.01181582]
 [ 0.         -0.00049881]]
[[ 0.          0.        ]
 [ 0.01181582 -0.00049881]]


In [29]:
def output(i):
    hidden_output=act(i@w1+b1)  # 1x2
    final_output=act(hidden_output@w2+b2)
    return final_output

In [30]:
k=np.array([0,0])
print(output(k))
k=np.array([1,0])
print(output(k))
k=np.array([0,1])
print(output(k))
k=np.array([1,1])
print(output(k))

[[0.60135381]]
[[0.6137226]]
[[0.58427664]]
[[0.59338099]]


In [31]:
test=np.array([[1,1],[0,0],[1,0],[0,1],[0,0]])
for i in test:
  print(np.round(output(i)))

[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]


In [32]:
import numpy as np

In [33]:
i=[1,2,3,4]
w=[[1,1,1,1],[2,2,2,2],[3,3,3,3]]
print(np.dot(i,np.array(w).T))
print(np.dot(w,i))

[10 20 30]
[10 20 30]


In [43]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[0],[0],[1]])


input_nodes=2
hidden_nodes=2
output_nodes=1

w1=np.random.uniform(low=-1,high=1,size=(input_nodes,hidden_nodes))
w2=np.random.uniform(low=-1,high=1,size=(hidden_nodes,output_nodes))

b1=np.random.uniform(low=-1,high=1,size=(1,hidden_nodes))
b2=np.random.uniform(low=-1,high=1,size=(1,output_nodes))

print(w1)
print(w2)
print(b1)
print(b2)

[[-0.57688043  0.74665858]
 [ 0.54581718 -0.27749508]]
[[0.14340194]
 [0.3097334 ]]
[[0.36896947 0.61864882]]
[[-0.10723194]]


In [44]:
def act(x):
    return 1/(1+ np.exp(-x))
def derivative(x):
    return x*(1-x)

In [49]:
l=1
for j in range(1000):
#     for i in range(len(x)):
        i=x
        t=y

        # i - 1x2 w1 2x4 o = 1x4 
        hidden_o=act(i@w1+b1) #1x4
        final_o=act(hidden_o@w2+b2) #1x1
    #     print(final_o)


        final_e=derivative(final_o)*(t-final_o) #1x1
        hidden_e=derivative(hidden_o)*(final_e@w2.T)  #should be 1x4

        #final_e 1x1 and hidden_o is 1x4
        #i is 1x2 and hidden_e is 1x4
        w2+=l*(hidden_o.T@final_e)   #should be 4x1
        w1+=l*(i.T@hidden_e)         #should be 2x4


        b2+=l*np.mean(final_e,axis=0)
        b1+=l*np.mean(hidden_e,axis=0)    


In [50]:
test=x
for i in test:
    print(predict(i))

[[0.00148427]]
[[0.03862863]]
[[0.03829347]]
[[0.91982385]]


In [47]:
def predict(x):
    hidden_o=act(x@w1+b1)
    final_o=act(hidden_o@w2+b2)
    return final_o
